services:
  _defaults:
    autowire: true
    bind:
      $projectFolder: '%kernel.project_dir%'
      $pdfInstanceLog: "@monolog.logger.huh_pdf_creator_instance_log"
      $bundleConfig: '%huh_pdf_creator%'

  Heimrichhannot\PdfCreatorBundle\:
    resource: '../../{DataContainer,Generator}/*'
    exclude: '../../Generator/PdfGeneratorContext.php'
    public: true

  Heimrichhannot\PdfCreatorBundle\EventListener\Contao\:
    resource: '../../EventListener/Contao/*'
    public: true

  Heimrichhannot\PdfCreatorBundle\SyndicationType\PdfCreatorSyndicationType:
    tags: ['huh.syndication_type.type']

  Heimrichhannot\PdfCreatorBundle\EventSubscriber\:
    resource: '../../EventSubscriber/*'
    autoconfigure: true