services:
  _defaults:
    autowire: true

  Heimrichhannot\PdfCreatorBundle\:
    resource: '../../{DataContainer,Generator}/*'
    exclude: '../../Generator/PdfGeneratorContext.php'
    public: true

  Heimrichhannot\PdfCreatorBundle\SyndicationType\PdfCreatorSyndicationType:
    tags: ['huh.syndication_type.type']

  Heimrichhannot\PdfCreatorBundle\EventSubscriber\:
    resource: '../../EventSubscriber/*'
    autoconfigure: true