services:
  _defaults:
    autowire: true
    bind:
      $projectFolder: '%kernel.project_dir%'
      $pdfInstanceLog: "@monolog.logger.huh_pdf_creator_instance_log"
      $bundleConfig: '%huh_pdf_creator%'

  Heimrichhannot\PdfCreatorBundle\:
    resource: '../../{DataContainer,EventListener,Generator}/*'
    exclude: '../../Generator/{PdfGeneratorContext.php}'
    autoconfigure: true
    public: true

  Heimrichhannot\PdfCreatorBundle\SyndicationType\PdfCreatorSyndicationType:
    tags: ['huh.syndication_type.type']