services:
  _defaults:
    autowire: true

  Heimrichhannot\PdfCreatorBundle\Generator\PdfGenerator:
    public: true

  Heimrichhannot\PdfCreatorBundle\DataContainer\:
    resource: '../../DataContainer/*'
    public: true